// <auto-generated />
using System;
using BMDbAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BMDbAPI.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BMDbAPI.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poster")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0645d7db-6072-4107-83b9-4d0a2866d2a7"),
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg",
                            Title = "The Shawshank Redemption",
                            Year = "1994"
                        },
                        new
                        {
                            Id = new Guid("8cf8ffc4-5290-4a72-a332-32078a779a1d"),
                            Director = "Francis Ford Coppola",
                            Genre = "Crime, Drama",
                            Poster = "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
                            Title = "The Godfather",
                            Year = "1972"
                        },
                        new
                        {
                            Id = new Guid("5298d16e-739a-46fe-b432-af0993887a7a"),
                            Director = "Christopher Nolan",
                            Genre = "Action, Crime, Drama",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
                            Title = "The Dark Knight",
                            Year = "2008"
                        },
                        new
                        {
                            Id = new Guid("c365cac0-6d7e-4181-9e36-d1cb594e3271"),
                            Director = "Christopher Nolan",
                            Genre = "Action, Adventure",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg",
                            Title = "The Dark Knight Rises",
                            Year = "2012"
                        },
                        new
                        {
                            Id = new Guid("dc17d0b3-6a2c-4389-b10e-c4c9e81b5504"),
                            Director = "Francis Ford Coppola",
                            Genre = "Crime, Drama",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
                            Title = "The Godfather: Part II",
                            Year = "1974"
                        },
                        new
                        {
                            Id = new Guid("b2f57cfb-1c4c-48e7-9cc1-b98330cfcf50"),
                            Director = "Peter Jackson",
                            Genre = "Action, Adventure, Drama",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
                            Title = "The Lord of the Rings: The Return of the King",
                            Year = "2003"
                        },
                        new
                        {
                            Id = new Guid("cb6967ad-8166-4e85-9abb-027d9a96a7e7"),
                            Director = "Quentin Tarantino",
                            Genre = "Crime, Drama",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
                            Title = "Pulp Fiction",
                            Year = "1994"
                        },
                        new
                        {
                            Id = new Guid("ffa7c587-f2c9-4c20-96a7-c13fd497f51a"),
                            Director = "Steven Spielberg",
                            Genre = "Biography, Drama, History",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
                            Title = "Schindler's List",
                            Year = "1993"
                        },
                        new
                        {
                            Id = new Guid("d480c22e-7906-4c4d-abcb-9e7c1d8b2fc8"),
                            Director = "Peter Jackson",
                            Genre = "Action, Adventure, Drama",
                            Poster = "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Year = "2001"
                        },
                        new
                        {
                            Id = new Guid("8245930e-2c01-4588-90ca-42294f499c8f"),
                            Director = "David Fincher",
                            Genre = "Drama",
                            Poster = "https://m.media-amazon.com/images/M/MV5BODQ0OWJiMzktYjNlYi00MzcwLThlZWMtMzRkYTY4ZDgxNzgxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
                            Title = "Fight Club",
                            Year = "1999"
                        },
                        new
                        {
                            Id = new Guid("f8d531e4-e74e-4d75-923e-2bd7beb89404"),
                            Director = "Lana Wachowski, Lilly Wachowski",
                            Genre = "Action, Sci-Fi",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg",
                            Title = "The Matrix",
                            Year = "1999"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
